name: Image copy

on: [push, pull_request]

jobs:
  run-shell-command:
    runs-on: ubuntu-latest
    steps:
      - name: download carvel imgpkg 
        run: |
          wget https://github.com/vmware-tanzu/carvel-imgpkg/releases/download/v0.7.0/imgpkg-linux-amd64
          sudo mv imgpkg-linux-amd64 /usr/bin/imgpkg
          
  
